import { useEffect, useState } from "react";
import { adminAuditEvents, adminDecideRefund, adminGenerations, adminInvoices, adminIssueInvoice, adminOrders, adminRefunds, adminUpdateUser, adminUsers, currentUser, type AuditEvent, type Generation, type Invoice, type Order, type RefundRequest, type User } from "../lib/api";

export function AdminPanel() {
  const [me,setMe]=useState<User|null>(null);const [users,setUsers]=useState<User[]>([]);const [orders,setOrders]=useState<Order[]>([]);const [generations,setGenerations]=useState<Generation[]>([]);const [audits,setAudits]=useState<AuditEvent[]>([]);const [refunds,setRefunds]=useState<RefundRequest[]>([]);const [invoices,setInvoices]=useState<Invoice[]>([]);const [message,setMessage]=useState("");
  const refresh=async()=>{const [nextUsers,nextOrders,nextGenerations,nextAudits,nextRefunds,nextInvoices]=await Promise.all([adminUsers(),adminOrders(),adminGenerations(),adminAuditEvents(),adminRefunds(),adminInvoices()]);setUsers(nextUsers);setOrders(nextOrders);setGenerations(nextGenerations);setAudits(nextAudits.slice().reverse().slice(0,50));setRefunds(nextRefunds);setInvoices(nextInvoices);};
  useEffect(()=>{const load=()=>void currentUser().then((user)=>{setMe(user);if(user?.role==="admin")void refresh().catch((error)=>setMessage(error.message));else{setUsers([]);setOrders([]);setGenerations([]);setAudits([]);}});load();window.addEventListener("auth-changed",load);return()=>window.removeEventListener("auth-changed",load);},[]);
  if(me?.role!=="admin")return null;
  const update=async(id:string,patch:{status?:"active"|"banned";membershipLevel?:"free"|"vip"})=>{try{const user=await adminUpdateUser(id,patch);setUsers((current)=>current.map((item)=>item.id===id?user:item));setMessage("用户已更新并写入审计");}catch(error){setMessage(error instanceof Error?error.message:"更新失败");}};
  return <section className="panel admin-panel"><div className="panel-heading"><h2>管理后台</h2><span>{users.length} 用户 · {orders.length} 订单 · {generations.length} 任务</span></div>{message&&<p className="panel-message">{message}</p>}<div className="admin-grid"><div><h3>用户与权益</h3><div className="admin-list">{users.map((user)=><div key={user.id}><span><b>{user.email}</b><small>{user.role} · {user.status} · {user.membershipLevel}</small></span><span><button type="button" onClick={()=>void update(user.id,{status:user.status==="active"?"banned":"active"})}>{user.status==="active"?"封禁":"解封"}</button><button type="button" onClick={()=>void update(user.id,{membershipLevel:user.membershipLevel==="vip"?"free":"vip"})}>{user.membershipLevel==="vip"?"取消 VIP":"授予 VIP"}</button></span></div>)}</div></div><div><h3>最近订单</h3><div className="admin-list">{orders.slice(0,20).map((order)=><div key={order.id}><span><b>{order.product}</b><small>{order.orderNo} · ¥{(order.amountCents/100).toFixed(2)} · {order.status}</small></span></div>)}</div></div><div><h3>退款与发票</h3><div className="admin-list">{refunds.filter((item)=>item.status==="pending").map((refund)=><div key={refund.id}><span><b>退款申请</b><small>{refund.reason} · {refund.orderId}</small></span><span><button type="button" onClick={()=>void adminDecideRefund(refund.id,"approved").then(()=>refresh())}>批准</button><button type="button" onClick={()=>void adminDecideRefund(refund.id,"rejected").then(()=>refresh())}>拒绝</button></span></div>)}{invoices.filter((item)=>item.status==="requested").map((invoice)=><div key={invoice.id}><span><b>{invoice.title}</b><small>{invoice.email} · {invoice.orderId}</small></span><button type="button" onClick={()=>void adminIssueInvoice(invoice.id).then(()=>refresh())}>标记已开票</button></div>)}</div></div><div><h3>安全与操作审计</h3><div className="admin-list audit-list">{audits.map((event)=><div key={event.id}><span><b>{event.type}</b><small>{new Date(event.createdAt).toLocaleString()} · {event.targetId||"-"}</small></span></div>)}</div></div></div></section>;
}
